nombreLabel=Name
fechaLabel=Date
estadoLabel=Status
departamentoLabel=Department
singularName=Document
saveLabel=Save
cancelLabel=Cancel
proveedorLabel=Provider
nroReferenciaLabel=Reference Number
curierLabel=Courier
numeroExpedienteLabel=File Number
juzgadoLabel=Court