appName=Document Catalog - Exercise
documentListTitle=Document List
statsLabel=Total documents created
languageEnglish=English
languageSpanish=Spanish
homeLabel=Home
listLabel=List
createLabel=Create
